[package]
name = "solana-sol-distributor"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bs58 = "0.5.1"
clap = "4.5.4"
solana-cli = "1.18.9"
solana-sdk = "1.18.9"
